artifacts:
  bird-rec-model:
    path: bird-rec-model
    type: model
stages:
  train:
    cmd: python src/train.py
    deps:
    - data/train.zip
    - src/train.py
    params:
    - train.epochs
    outs:
    - bird-rec-model/
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - bird-rec-model
    - data/test.zip
    - src/evaluate.py
metrics:
- live/train/metrics.json
plots:
- live/train/plots/metrics:
    x: step
- live/eval/plots/metrics:
    x: step
- live/eval/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label